import {
  User,
  UserRole,
  Organization,
  Kitchen,
  FoodProductionRecord,
  FoodConsumptionRecord,
  FoodWasteRecord,
  FoodInventoryItem,
  SurplusListing,
  NGOPartner,
  PickupOrder,
  AppNotification,
  ImpactMetrics,
  AIPredictionResult,
} from '../types/database';

export const INITIAL_USERS: Record<UserRole, User> = {
  kitchen_manager: {
    id: 'usr-km-1',
    name: 'Rajesh Sharma',
    email: 'kitchen.mgr@savebite.org',
    role: 'kitchen_manager',
    organizationId: 'org-kit-1',
    phone: '+91 98765 43210',
  },
  food_processing_unit: {
    id: 'usr-fpu-1',
    name: 'Priya Mehra',
    email: 'operations@sunriseprocessors.com',
    role: 'food_processing_unit',
    organizationId: 'org-fpu-1',
    phone: '+91 98765 11223',
  },
  ngo_food_bank: {
    id: 'usr-ngo-1',
    name: 'Anita Desai',
    email: 'anita@hopefoodbank.org',
    role: 'ngo_food_bank',
    organizationId: 'org-ngo-1',
    phone: '+91 98111 22334',
  },
  pickup_partner: {
    id: 'usr-pickup-1',
    name: 'Ramesh Patel',
    email: 'ramesh@swiftlogistics.in',
    role: 'pickup_partner',
    organizationId: 'org-log-1',
    phone: '+91 98222 33445',
  },
  administrator: {
    id: 'usr-admin-1',
    name: 'Dr. Sameer Joshi',
    email: 'admin@savebite.gov.in',
    role: 'administrator',
    organizationId: 'org-admin-1',
    phone: '+91 99000 88776',
  },
};

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-kit-1',
    name: 'Green Campus Central Dining',
    type: 'college_hostel',
    address: 'Academic Zone, Tech Institute, Sector 62, Noida, UP',
    lat: 28.628,
    lng: 77.364,
    contactPerson: 'Rajesh Sharma',
    phone: '+91 98765 43210',
    verified: true,
    dailyCapacity: 1200,
  },
  {
    id: 'org-fpu-1',
    name: 'Sunrise Agro & Food Processing Hub',
    type: 'food_processing_unit',
    address: 'Plot 44, Food Park Industrial Area, Greater Noida',
    lat: 28.535,
    lng: 77.391,
    contactPerson: 'Priya Mehra',
    phone: '+91 98765 11223',
    verified: true,
    dailyCapacity: 5000,
  },
  {
    id: 'org-ngo-1',
    name: 'Hope Food Bank & Community Center',
    type: 'food_bank',
    address: 'Building 12, Seva Marg, Mayur Vihar, Delhi NCR',
    lat: 28.601,
    lng: 77.302,
    contactPerson: 'Anita Desai',
    phone: '+91 98111 22334',
    verified: true,
    dailyCapacity: 350,
  },
  {
    id: 'org-ngo-2',
    name: 'Community Care NGO',
    type: 'ngo',
    address: '4th Cross, Vivek Vihar, East Delhi',
    lat: 28.665,
    lng: 77.319,
    contactPerson: 'Vikram Seth',
    phone: '+91 98444 55667',
    verified: true,
    dailyCapacity: 200,
  },
  {
    id: 'org-ngo-3',
    name: 'City Shelter & Children Mission',
    type: 'ngo',
    address: 'Near Metro Station, Anand Vihar, Delhi',
    lat: 28.647,
    lng: 77.315,
    contactPerson: 'Sister Mary',
    phone: '+91 98666 77889',
    verified: true,
    dailyCapacity: 180,
  },
  {
    id: 'org-log-1',
    name: 'SwiftLogistics Volunteer Fleet',
    type: 'logistics_partner',
    address: 'Logistics Park Hub 4, Noida',
    lat: 28.585,
    lng: 77.345,
    contactPerson: 'Sunil Rao',
    phone: '+91 98222 33445',
    verified: true,
    dailyCapacity: 600,
  },
];

export const INITIAL_NGO_PARTNERS: NGOPartner[] = [
  {
    id: 'ngo-1',
    name: 'Hope Food Bank',
    type: 'Food Bank',
    address: 'Building 12, Seva Marg, Mayur Vihar',
    lat: 28.601,
    lng: 77.302,
    distanceKm: 2.4,
    intakeCapacityMeals: 100,
    activeVolunteerDrivers: 3,
    pickupAvailability: 'Available',
    operatingHours: '8:00 AM – 9:00 PM',
    matchScore: 96,
    matchReason: 'Sufficient capacity (100 meals), closest location (2.4 km), and verified fast cold-chain insulated carrier ready.',
    verifiedFSSAI: true,
  },
  {
    id: 'ngo-2',
    name: 'Community Care NGO',
    type: 'Community Kitchen',
    address: '4th Cross, Vivek Vihar, East Delhi',
    lat: 28.665,
    lng: 77.319,
    distanceKm: 4.1,
    intakeCapacityMeals: 70,
    activeVolunteerDrivers: 2,
    pickupAvailability: 'Available',
    operatingHours: '10:00 AM – 8:00 PM',
    matchScore: 89,
    matchReason: 'Can receive 70 meals immediately; volunteer van available for pickup within 35 minutes.',
    verifiedFSSAI: true,
  },
  {
    id: 'ngo-3',
    name: 'City Shelter',
    type: 'Children Shelter',
    address: 'Near Metro Station, Anand Vihar',
    lat: 28.647,
    lng: 77.315,
    distanceKm: 6.2,
    intakeCapacityMeals: 120,
    activeVolunteerDrivers: 0,
    pickupAvailability: 'Unavailable',
    operatingHours: '9:00 AM – 6:00 PM',
    matchScore: 72,
    matchReason: 'High demand for meals but currently lacks internal pickup vehicle; requires external logistics assignment.',
    verifiedFSSAI: true,
  },
  {
    id: 'ngo-4',
    name: 'Annapoorna Seva Trust',
    type: 'Food Bank',
    address: 'Civil Lines, Old City Sector',
    lat: 28.675,
    lng: 77.225,
    distanceKm: 5.5,
    intakeCapacityMeals: 150,
    activeVolunteerDrivers: 4,
    pickupAvailability: 'Available',
    operatingHours: '7:00 AM – 10:00 PM',
    matchScore: 85,
    matchReason: 'Large capacity and flexible pickup windows with temperature-controlled containers.',
    verifiedFSSAI: true,
  },
];

export const INITIAL_SURPLUS_LISTINGS: SurplusListing[] = [
  {
    id: 'surp-101',
    kitchenId: 'org-kit-1',
    kitchenName: 'Green Campus Central Dining',
    foodName: 'Nutritious Dal Makhani & Jeera Rice with Roti',
    category: 'Cooked Meals',
    quantityMeals: 90,
    quantityKg: 36,
    dietaryType: 'Vegetarian',
    preparationTime: '12:30 PM Today',
    availableUntil: '5:30 PM Today',
    storageCondition: 'Hot Held (65°C+)',
    pickupLocation: 'Rear Loading Dock Gate 3, Dining Hall, Green Campus',
    pickupLat: 28.628,
    pickupLng: 77.364,
    status: 'Available',
    foodSafetyVerified: true,
    createdAt: '1:45 PM Today',
    notes: 'Kept in insulated commercial warmers at 68°C. Packed cleanly in stainless steel food-grade carriers.',
  },
  {
    id: 'surp-102',
    kitchenId: 'org-kit-1',
    kitchenName: 'Green Campus Central Dining',
    foodName: 'Fresh Mixed Fruit Custard & Whole Wheat Buns',
    category: 'Bakery & Bread',
    quantityMeals: 35,
    quantityKg: 14,
    dietaryType: 'Vegetarian',
    preparationTime: '11:00 AM Today',
    availableUntil: '7:00 PM Today',
    storageCondition: 'Refrigerated (4°C)',
    pickupLocation: 'Cold Storage Pantry, Green Campus',
    pickupLat: 28.628,
    pickupLng: 77.364,
    status: 'Available',
    foodSafetyVerified: true,
    createdAt: '2:15 PM Today',
    notes: 'Sealed individual packaging.',
  },
  {
    id: 'surp-103',
    kitchenId: 'org-kit-1',
    kitchenName: 'Green Campus Central Dining',
    foodName: 'Steamed Idli & Sambar (Breakfast Surplus)',
    category: 'Cooked Meals',
    quantityMeals: 40,
    quantityKg: 16,
    dietaryType: 'Vegetarian',
    preparationTime: '8:00 AM Today',
    availableUntil: '1:00 PM Today',
    storageCondition: 'Hot Held (65°C+)',
    pickupLocation: 'Kitchen Dispatch Area',
    pickupLat: 28.628,
    pickupLng: 77.364,
    status: 'Redistributed',
    matchedRecipientId: 'ngo-1',
    matchedRecipientName: 'Hope Food Bank',
    pickupId: 'pk-9901',
    foodSafetyVerified: true,
    createdAt: '9:30 AM Today',
  },
];

export const INITIAL_PICKUPS: PickupOrder[] = [
  {
    id: 'pk-8841',
    surplusListingId: 'surp-101',
    foodDescription: '90 Vegetarian Meals (Dal & Rice)',
    quantityMeals: 90,
    pickupLocation: 'Green Campus Central Dining, Gate 3',
    destinationName: 'Hope Food Bank',
    destinationAddress: 'Building 12, Seva Marg, Mayur Vihar',
    pickupTime: '4:15 PM Today',
    assignedPartner: 'SwiftLogistics Clean Fleet',
    driverName: 'Ramesh Patel',
    driverPhone: '+91 98222 33445',
    vehicleNumber: 'DL-01-EF-4290 (Insulated EV Van)',
    temperatureAtPickup: 66.5,
    status: 'Assigned',
    estimatedArrivalMin: 18,
    timeline: [
      { status: 'Pending', timestamp: '2:10 PM', note: 'AI matched with Hope Food Bank' },
      { status: 'Assigned', timestamp: '2:25 PM', note: 'Driver Ramesh Patel assigned' },
    ],
  },
  {
    id: 'pk-9901',
    surplusListingId: 'surp-103',
    foodDescription: '40 Vegetarian Breakfast Meals',
    quantityMeals: 40,
    pickupLocation: 'Green Campus Central Dining',
    destinationName: 'Hope Food Bank',
    destinationAddress: 'Building 12, Seva Marg, Mayur Vihar',
    pickupTime: '10:15 AM Today',
    assignedPartner: 'SwiftLogistics Volunteer Fleet',
    driverName: 'Sanjay Rawat',
    driverPhone: '+91 98333 44556',
    vehicleNumber: 'DL-04-AB-1102',
    temperatureAtPickup: 67.0,
    status: 'Delivered',
    estimatedArrivalMin: 0,
    timeline: [
      { status: 'Pending', timestamp: '9:35 AM', note: 'Created' },
      { status: 'Assigned', timestamp: '9:45 AM', note: 'Assigned to driver' },
      { status: 'On the Way', timestamp: '10:00 AM', note: 'Driver reached pickup location' },
      { status: 'Collected', timestamp: '10:18 AM', note: 'Food handed over at 67°C' },
      { status: 'Delivered', timestamp: '10:45 AM', note: 'Safely delivered to Hope Food Bank pantry' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'surplus',
    title: 'Surplus Detected',
    message: '125 surplus meals are available from today’s lunch service.',
    timestamp: '15 mins ago',
    read: false,
    actionRoute: 'surplus',
  },
  {
    id: 'notif-2',
    type: 'match',
    title: 'Match Confirmed',
    message: 'Hope Food Bank accepted your food offer of 90 meals.',
    timestamp: '35 mins ago',
    read: false,
    actionRoute: 'redistribution',
  },
  {
    id: 'notif-3',
    type: 'pickup',
    title: 'Pickup Scheduled',
    message: 'Pickup scheduled for 4:15 PM by SwiftLogistics (Driver: Ramesh).',
    timestamp: '1 hour ago',
    read: false,
    actionRoute: 'pickups',
  },
  {
    id: 'notif-4',
    type: 'waste_alert',
    title: 'AI Waste Alert',
    message: 'AI detected unusually high plate waste (35 kg) on vegetable side dish today.',
    timestamp: '2 hours ago',
    read: false,
    actionRoute: 'waste',
  },
  {
    id: 'notif-5',
    type: 'ai_insight',
    title: 'Demand Prediction Ready',
    message: 'Tomorrow\'s recommended preparation quantity is 890 meals.',
    timestamp: '3 hours ago',
    read: true,
    actionRoute: 'prediction',
  },
];

export const INITIAL_IMPACT_METRICS: ImpactMetrics = {
  totalMealsSaved: 12450,
  totalFoodRedistributedMeals: 8920,
  foodWasteReducedKg: 3280,
  moneySavedRupees: 185000,
  co2EmissionsPreventedKg: 7850,
  waterSavedLiters: 1940000,
  landfillsAvoidedTons: 3.4,
  activeKitchens: 48,
  activeProcessingUnits: 14,
  activeNGOs: 62,
  activePickupPartners: 31,
};

export const INITIAL_WASTE_RECORDS: FoodWasteRecord[] = [
  {
    id: 'w-1',
    kitchenId: 'org-kit-1',
    date: 'Today',
    mealType: 'Lunch',
    category: 'Overproduction',
    quantityKg: 18,
    estimatedCostLoss: 1440,
    primaryCause: 'Lower student turn-up due to sudden rain shower',
    preventativeAction: 'Incorporate weather dampening factor into morning production scheduling',
    loggedBy: 'Rajesh Sharma',
  },
  {
    id: 'w-2',
    kitchenId: 'org-kit-1',
    date: 'Today',
    mealType: 'Lunch',
    category: 'Plate Waste',
    quantityKg: 11,
    estimatedCostLoss: 880,
    primaryCause: 'Oversized rice ladles causing excessive diner serving',
    preventativeAction: 'Switch to standard 120g serving spoons and self-serve seconds',
    loggedBy: 'Rajesh Sharma',
  },
  {
    id: 'w-3',
    kitchenId: 'org-kit-1',
    date: 'Today',
    mealType: 'Breakfast',
    category: 'Preparation Waste',
    quantityKg: 4,
    estimatedCostLoss: 280,
    primaryCause: 'Vegetable peelings and trimming scrap',
    preventativeAction: 'Compost kitchen trimmings in institutional organic digestor',
    loggedBy: 'Amit Cook',
  },
  {
    id: 'w-4',
    kitchenId: 'org-kit-1',
    date: 'Today',
    mealType: 'Breakfast',
    category: 'Spoilage',
    quantityKg: 2,
    estimatedCostLoss: 180,
    primaryCause: 'Yogurt container seal damage during transit',
    preventativeAction: 'Return invoice claim to dairy vendor',
    loggedBy: 'Store In-charge',
  },
];

export const INITIAL_INVENTORY: FoodInventoryItem[] = [
  {
    id: 'inv-1',
    orgId: 'org-fpu-1',
    productName: 'Fortified Wheat Flour (Chakki Atta)',
    category: 'Raw Grains',
    batchNumber: 'BATCH-2026-088',
    quantity: 650,
    unit: 'kg',
    receivedDate: '2026-08-20',
    expiryDate: '2026-09-22',
    storageTemp: 'Ambient',
    daysToExpiry: 7,
    nearExpiryAlert: true,
  },
  {
    id: 'inv-2',
    orgId: 'org-fpu-1',
    productName: 'Pasteurized Probiotic Curd Cups',
    category: 'Dairy',
    batchNumber: 'DAIRY-09-41',
    quantity: 180,
    unit: 'packets',
    receivedDate: '2026-09-10',
    expiryDate: '2026-09-18',
    storageTemp: 'Refrigerated 4°C',
    daysToExpiry: 3,
    nearExpiryAlert: true,
  },
  {
    id: 'inv-3',
    orgId: 'org-fpu-1',
    productName: 'Whole Grain Bakery Loaves',
    category: 'Packaged Goods',
    batchNumber: 'BAKE-14-99',
    quantity: 95,
    unit: 'packets',
    receivedDate: '2026-09-14',
    expiryDate: '2026-09-17',
    storageTemp: 'Ambient',
    daysToExpiry: 2,
    nearExpiryAlert: true,
  },
  {
    id: 'inv-4',
    orgId: 'org-fpu-1',
    productName: 'Yellow Lentils (Toor Dal)',
    category: 'Raw Grains',
    batchNumber: 'GRAIN-01-2026',
    quantity: 1200,
    unit: 'kg',
    receivedDate: '2026-09-01',
    expiryDate: '2027-03-01',
    storageTemp: 'Ambient',
    daysToExpiry: 167,
    nearExpiryAlert: false,
  },
];
